In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

tickers = ["SPY", "QQQ", "TLT", "GLD"]

market_data = yf.download(
    tickers=tickers,
    start="2019-01-01",
    end="2026-01-01",
    auto_adjust=True,
    progress=True
)

market_data.head()

[*********************100%***********************]  4 of 4 completed

Price            Close                                           High  \
Ticker             GLD         QQQ         SPY        TLT         GLD
Date
2019-01-02  121.330002  147.878342  223.806000  97.560425  121.750000
2019-01-03  122.430000  143.047104  218.465332  98.670639  122.459999
2019-01-04  121.440002  149.167297  225.782990  97.528481  121.599998
2019-01-07  121.860001  150.943253  227.563187  97.240959  122.220001
2019-01-08  121.529999  152.308624  229.701218  96.985397  121.709999

Price                                                 Low              \
Ticker             QQQ         SPY        TLT         GLD         QQQ
Date
2019-01-02  148.709007  224.727430  97.568413  120.879997  144.059170
2019-01-03  146.331580  222.365700  98.926221  121.730003  142.732020
2019-01-04  149.902492  226.427088  97.887890  120.690002  144.880286
2019-01-07  151.678447  228.967670  97.959785  121.570000  149.052766
2019-01-08  152.871949  230.184298  97.392733  121.059998  150.093497

Price                                    Open                          \
Ticker             SPY        TLT         GLD         QQQ         SPY
Date
2019-01-02  220.021930  96.913479  121.349998  144.164198  220.048767
2019-01-03  217.982251  97.624352  121.779999  145.701427  222.061533
2019-01-04  221.113282  97.161082  121.320000  145.453153  221.489004
2019-01-07  225.156765  97.137131  122.160004  149.539705  226.051345
2019-01-08  227.223242  96.953449  121.150002  152.327710  229.745963

Price                    Volume
Ticker            TLT       GLD       QQQ        SPY       TLT
Date
2019-01-02  97.169067  12776200  58576700  126925200  19841500
2019-01-03  97.672272  15440800  74820200  144140700  21187000
2019-01-04  97.712177  13334000  74709300  142628800  12970200
2019-01-07  97.935825   7473600  52059300  103139100   8498100
2019-01-08  97.193059   7643100  49388700  102512600   7737100

In [2]:
market_data.tail()

Price            Close                                           High  \
Ticker             GLD         QQQ         SPY        TLT         GLD
Date
2025-12-24  411.929993  622.460205  686.730530  85.405441  412.630005
2025-12-26  416.739990  622.420349  686.660889  85.124084  418.450012
2025-12-29  398.600006  619.407410  684.213867  85.444252  403.760010
2025-12-30  398.890015  617.970764  683.378296  85.240509  403.799988
2025-12-31  396.309998  612.862854  678.315247  84.561386  400.130005

Price                                                 Low              \
Ticker             QQQ         SPY        TLT         GLD         QQQ
Date
2025-12-24  622.809417  687.178163  85.453954  408.829987  620.255389
2025-12-26  624.046514  688.003728  85.541265  414.750000  621.672116
2025-12-29  621.312944  685.556767  85.444252  395.329987  617.272436
2025-12-30  620.714286  684.920090  85.415143  398.559998  617.761237
2025-12-31  618.499569  683.726492  85.289025  395.589996  612.603457

Price                                    Open                          \
Ticker             SPY        TLT         GLD         QQQ         SPY
Date
2025-12-24  684.164151  85.036773  412.250000  620.524773  684.313382
2025-12-26  685.626408  84.988259  416.480011  623.188494  686.989161
2025-12-29  682.443308  85.172601  403.660004  618.639204  683.905508
2025-12-30  682.950576  85.056171  403.600006  618.379832  683.815972
2025-12-31  678.106396  84.532274  398.600006  618.190301  683.507684

Price                    Volume
Ticker            TLT       GLD       QQQ       SPY       TLT
Date
2025-12-24  85.143494   6718400  18468700  39445600  25942000
2025-12-26  85.473352  10476200  28959800  41613300  26522700
2025-12-29  85.327827  20679200  32458300  62559500  29399800
2025-12-30  85.124084  10179000  31226800  47160700  25106800
2025-12-31  85.065879  10194700  40746500  74144800  36500000

In [3]:
market_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1760 entries, 2019-01-02 to 2025-12-31
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   (Close, GLD)   1760 non-null   float64
 1   (Close, QQQ)   1760 non-null   float64
 2   (Close, SPY)   1760 non-null   float64
 3   (Close, TLT)   1760 non-null   float64
 4   (High, GLD)    1760 non-null   float64
 5   (High, QQQ)    1760 non-null   float64
 6   (High, SPY)    1760 non-null   float64
 7   (High, TLT)    1760 non-null   float64
 8   (Low, GLD)     1760 non-null   float64
 9   (Low, QQQ)     1760 non-null   float64
 10  (Low, SPY)     1760 non-null   float64
 11  (Low, TLT)     1760 non-null   float64
 12  (Open, GLD)    1760 non-null   float64
 13  (Open, QQQ)    1760 non-null   float64
 14  (Open, SPY)    1760 non-null   float64
 15  (Open, TLT)    1760 non-null   float64
 16  (Volume, GLD)  1760 non-null   int64
 17  (Volume, QQQ)  1760 non-null   int64
 18  (Volume, SPY)  1760 non-null   int64
 19  (Volume, TLT)  1760 non-null   int64
dtypes: float64(16), int64(4)
memory usage: 288.8 KB

In [4]:
prices = market_data["Close"]
prices.head()

Ticker             GLD         QQQ         SPY        TLT
Date
2019-01-02  121.330002  147.878342  223.806000  97.560425
2019-01-03  122.430000  143.047104  218.465332  98.670639
2019-01-04  121.440002  149.167297  225.782990  97.528481
2019-01-07  121.860001  150.943253  227.563187  97.240959
2019-01-08  121.529999  152.308624  229.701218  96.985397

In [5]:
prices["SPY"].head()

Date
2019-01-02    223.806000
2019-01-03    218.465332
2019-01-04    225.782990
2019-01-07    227.563187
2019-01-08    229.701218
Name: SPY, dtype: float64

In [6]:
spy_returns = prices["SPY"].pct_change()
spy_returns.head()

Date
2019-01-02         NaN
2019-01-03   -0.023863
2019-01-04    0.033496
2019-01-07    0.007885
2019-01-08    0.009395
Name: SPY, dtype: float64

In [7]:
spy_returns.describe()

count    1759.000000
mean        0.000708
std         0.012461
min        -0.109424
25%        -0.004297
50%         0.000985
75%         0.006692
max         0.105019
Name: SPY, dtype: float64

In [8]:
spy_returns.idxmin()

Timestamp('2020-03-16 00:00:00')

In [9]:
spy_returns.loc["2020-03-16"]

-0.1094236830074734

In [10]:
prices.loc["2020-03-16", "SPY"]

218.6278839111328

In [11]:
prices.loc["2020-03-13", "SPY"]

245.49034118652344

In [12]:
march_13 = prices.loc["2020-03-13", "SPY"]
march_16 = prices.loc["2020-03-16", "SPY"]

return_calculation = (march_16 - march_13) / march_13

print(return_calculation)

-0.10942368300747338

In [13]:
returns = prices.pct_change()
returns.head()

Ticker           GLD       QQQ       SPY       TLT
Date
2019-01-02       NaN       NaN       NaN       NaN
2019-01-03  0.009066 -0.032670 -0.023863  0.011380
2019-01-04 -0.008086  0.042784  0.033496 -0.011575
2019-01-07  0.003458  0.011906  0.007885 -0.002948
2019-01-08 -0.002708  0.009046  0.009395 -0.002628

In [14]:
returns = returns.dropna()
returns.head()

Ticker           GLD       QQQ       SPY       TLT
Date
2019-01-03  0.009066 -0.032670 -0.023863  0.011380
2019-01-04 -0.008086  0.042784  0.033496 -0.011575
2019-01-07  0.003458  0.011906  0.007885 -0.002948
2019-01-08 -0.002708  0.009046  0.009395 -0.002628
2019-01-09  0.006418  0.008149  0.004673 -0.001565

In [15]:
correlation = returns.corr()
correlation

Ticker       GLD       QQQ       SPY       TLT
Ticker
GLD     1.000000  0.114194  0.105339  0.254869
QQQ     0.114194  1.000000  0.936984 -0.094042
SPY     0.105339  0.936984  1.000000 -0.143220
TLT     0.254869 -0.094042 -0.143220  1.000000

In [16]:
returns.std()

Ticker
GLD    0.009925
QQQ    0.015258
SPY    0.012461
TLT    0.010378
dtype: float64

In [17]:
returns.mean()

Ticker
GLD    0.000722
QQQ    0.000925
SPY    0.000708
TLT   -0.000028
dtype: float64

In [18]:
summary=pd.DataFrame({"Average Daily Return":returns.mean(),"Daily Volatility":returns.std()}) 
summary

        Average Daily Return  Daily Volatility
Ticker
GLD                 0.000722          0.009925
QQQ                 0.000925          0.015258
SPY                 0.000708          0.012461
TLT                -0.000028          0.010378

In [19]:
summary_percent = summary * 100
summary_percent

        Average Daily Return  Daily Volatility
Ticker
GLD                 0.072247          0.992543
QQQ                 0.092517          1.525831
SPY                 0.070840          1.246111
TLT                -0.002751          1.037770

In [20]:
annualized_return = returns.mean() * 252

annualized_return

Ticker
GLD    0.182063
QQQ    0.233142
SPY    0.178518
TLT   -0.006933
dtype: float64

In [21]:
annualized_volatility = returns.std() * np.sqrt(252)

annualized_volatility

Ticker
GLD    0.157561
QQQ    0.242218
SPY    0.197814
TLT    0.164741
dtype: float64

In [22]:
summary = pd.DataFrame({
    "Annualized Return": annualized_return,
    "Annualized Volatility": annualized_volatility
})

summary

        Annualized Return  Annualized Volatility
Ticker
GLD              0.182063               0.157561
QQQ              0.233142               0.242218
SPY              0.178518               0.197814
TLT             -0.006933               0.164741

In [24]:
project_path = r"C:\Users\Bawan Singh\OneDrive\Documents\Arshleen\market-portfolio-risk-analysis"

returns.to_csv(
    project_path + r"\data\processed\daily_returns.csv"
)

In [25]:
import os

os.getcwd()

'C:\\Users\\Bawan Singh'

In [26]:
import os

project_path = r"C:\Users\Bawan Singh\OneDrive\Documents\Arshleen\market-portfolio-risk-analysis"

os.makedirs(os.path.join(project_path, "data", "processed"), exist_ok=True)

In [27]:
returns.to_csv(
    os.path.join(project_path, "data", "processed", "daily_returns.csv")
)

In [28]:
os.path.exists(
    os.path.join(project_path, "data", "processed", "daily_returns.csv")
)

True

In [29]:
project_path = r"C:\Users\Bawan Singh\OneDrive\Documents\Arshleen\market-portfolio-risk-analysis"

returns = pd.read_csv(
    project_path + r"\data\processed\daily_returns.csv",
    index_col=0,
    parse_dates=True
)

In [30]:
returns.head()

                 GLD       QQQ       SPY       TLT
Date
2019-01-03  0.009066 -0.032670 -0.023863  0.011380
2019-01-04 -0.008086  0.042784  0.033496 -0.011575
2019-01-07  0.003458  0.011906  0.007885 -0.002948
2019-01-08 -0.002708  0.009046  0.009395 -0.002628
2019-01-09  0.006418  0.008149  0.004673 -0.001565